include("univariate/equal_rates.jl")
include("univariate/unequal_rates.jl")
include("univariate/univariate.jl")

include("gradient/birth_rate_zero.jl")
include("gradient/death_rate_zero.jl")
include("gradient/equal_rates.jl")
include("gradient/unequal_rates.jl")
include("gradient/gradient.jl")

include("gradient_hessian/birth_rate_zero.jl")
include("gradient_hessian/death_rate_zero.jl")
include("gradient_hessian/equal_rates.jl")
include("gradient_hessian/unequal_rates.jl")
include("gradient_hessian/gradient_hessian.jl")
